export default {
  HOMES_RECEIVED: 'HOMES_RECEIVED',
  HOME_RECEIVED: 'HOME_RECEIVED',
  HOME_LOADING: 'HOME_LOADING',
  USER_REGISTERED: 'USER_REGISTERED',
  USER_LOGGEDIN: 'USER_LOGGEDIN',
  USER_LOGOUT: 'USER_LOGOUT'
}
